openapi: 3.0.0
info:
  description: Item Master & Barcodes
  version: 1.0.0
  title: Item Master
  termsOfService: http://api.giorgioarmani.it/terms/
  contact:
    email: apiteam@giorgioarmani.it
  license:
    name: XXXX
    url: http://api.giorgioarmani.it/licenses/LICENSE-API.html
tags:
  - name: item-master
    description: Armani Pproduct Catalog
    externalDocs:
      description: Find out more
      url: http://api.giorgioarmani.it/docs
paths:
  /items:
    get:
      tags:
        - item
      summary: Return all Items for a given Year/Season
      description: Return active items
      parameters:
        - name: year
          in: query
          description: Year values that need to be considered for filter
          required: true
          explode: true
          schema:
            type: array
            items:
              type: string
              default: "2022"
        - name: season
          in: query
          description: Season values that need to be considered for filter
          required: true
          explode: true
          schema:
            type: array
            items:
              type: string
              default: SS
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/item"
            application/xml:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/item"
        "400":
          description: Invalid status value
      security:
        - api_key: []
  /barcodes:
    get:
      tags:
        - barcode
      summary: Return all Barcode for a given Item
      description: Return active barcodes
      parameters:
        - name: sku
          in: query
          description: sku
          required: true
          explode: true
          schema:
            type: array
            items:
              type: string
              default: ""
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/barcode"
            application/xml:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/barcode"
        "400":
          description: Invalid status value
      security:
        - api_key: []
externalDocs:
  description: Find out more about Giorgio Armani public APIs
  url: http://api.giorgioarmani.com
servers:
  - url: https://api.giorgioarmani.it/asfolcini/item-master/1.0.0
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
  schemas:
    localized-message:
      type: object
      properties:
        language:
          type: string
          example: en
        description:
          type: string
          example: This is an english message
    product:
      type: object
      properties:
        id:
          type: string
          example: "629"
        description:
          type: array
          example:
            - language: en
              description: SNEAKERS
            - language: it
              description: Scarpe da ginnastica
          items:
            $ref: "#/components/schemas/localized-message"
    product-type:
      type: object
      properties:
        id:
          type: string
          example: "40"
        description:
          type: array
          example:
            - language: en
              description: LEATHER
            - language: it
              description: Pelle
          items:
            $ref: "#/components/schemas/localized-message"
    product-kind:
      type: object
      properties:
        id:
          type: string
          example: A21
        description:
          type: array
          example:
            - language: en
              description: SNEAKER HIGH TOP
            - language: it
              description: Scarpe da ginnastica alte
          items:
            $ref: "#/components/schemas/localized-message"
    merchandise-category:
      type: object
      properties:
        id:
          type: string
        description:
          type: array
          example:
            - language: en
              description: SHOES
            - language: it
              description: Scarpe
          items:
            $ref: "#/components/schemas/localized-message"
    merchandise-group:
      type: object
      properties:
        id:
          type: string
        description:
          type: array
          example:
            - language: en
              description: SHOES
            - language: it
              description: Scarpe
          items:
            $ref: "#/components/schemas/localized-message"
    category:
      type: object
      properties:
        id:
          type: string
        description:
          type: array
          example:
            - language: en
              description: SHOES
            - language: it
              description: Scarpe
          items:
            $ref: "#/components/schemas/localized-message"
    brand:
      type: object
      properties:
        id:
          type: string
          example: "10"
        description:
          type: string
          example: Giorgio Armani
    seasonality:
      type: object
      properties:
        id: {}
        description:
          type: array
          example:
            - language: en
              description: Repurposed
            - language: it
              description: Riproposto
          items:
            $ref: "#/components/schemas/localized-message"
      description: Seasonality
    gender:
      type: object
      properties:
        id: {}
        description:
          type: array
          example:
            - language: en
              description: Man
            - language: it
              description: Uomo
          items:
            $ref: "#/components/schemas/localized-message"
      description: Gender
    item-status:
      type: object
      properties:
        id: {}
        description:
          type: array
          example:
            - language: en
              description: Active
            - language: it
              description: Attivo
          items:
            $ref: "#/components/schemas/localized-message"
        starting-date:
          type: string
          format: date-time
      description: Item Status
    barcode:
      type: object
      properties:
        sku:
          type: string
          example: XYZ010XOI69 00102N
        barcode:
          type: integer
          example: 8054804724299
        barcode-type:
          type: string
          example: GTIN13
        main:
          type: boolean
          default: false
      description: barcodes
    season:
      type: object
      properties:
        id:
          type: string
          example: FW22
        year:
          type: integer
          format: int32
          example: 2022
        description:
          type: array
          example:
            - language: en
              description: Fall/Winter
            - language: it
              description: Autunno/Inverno
          items:
            $ref: "#/components/schemas/localized-message"
      description: Year/Season
    madein:
      type: object
      properties:
        id:
          type: string
          example: ITA
        description:
          type: array
          example:
            - language: en
              description: Italy
            - language: it
              description: Italia
          items:
            $ref: "#/components/schemas/localized-message"
      description: Item Master madein, it might be different from production made-in
    division:
      type: object
      properties:
        id:
          type: string
          example: JB
        description:
          type: array
          example:
            - language: en
              description: Emporio Armani Boy
            - language: it
              description: Emporio Armani Bimbo
          items:
            $ref: "#/components/schemas/localized-message"
      description: Business Division
    collection:
      type: object
      properties:
        id:
          type: string
          example: JB
        description:
          type: array
          example:
            - language: en
              description: EA Boy
            - language: it
              description: EA Bimbo
          items:
            $ref: "#/components/schemas/localized-message"
      description: Collection
    theme:
      type: object
      properties:
        id:
          type: string
          example: "28"
        description:
          type: array
          example:
            - language: en
              description: Ex.2 Dl.8
            - language: it
              description: ""
          items:
            $ref: "#/components/schemas/localized-message"
      description: Theme
    cites:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 4
        description:
          type: array
          example:
            - language: en
              description: Mother of Pearl
            - language: it
              description: Madre Perla
          items:
            $ref: "#/components/schemas/localized-message"
      description: Washington Declaration
    underline:
      type: object
      properties:
        id:
          type: string
          example: "00"
        description:
          type: array
          example:
            - language: en
              description: Collection
            - language: it
              description: Collezione
          items:
            $ref: "#/components/schemas/localized-message"
    style:
      type: object
      properties:
        id:
          type: string
          example: XYZ010
        description:
          type: array
          example:
            - language: en
              description: XYZ010
            - language: it
              description: XYZ010
          items:
            $ref: "#/components/schemas/localized-message"
    fabric:
      type: object
      properties:
        id:
          type: string
          example: XOI69
        description:
          type: array
          example:
            - language: en
              description: XOI69
            - language: it
              description: XOI69
          items:
            $ref: "#/components/schemas/localized-message"
    color:
      type: object
      properties:
        id:
          type: string
          example: "001"
        description:
          type: array
          example:
            - language: en
              description: Black
            - language: it
              description: Nero
          items:
            $ref: "#/components/schemas/localized-message"
    drop:
      type: object
      properties:
        id:
          type: string
          example: N
        description:
          type: array
          example:
            - language: en
              description: ""
            - language: it
              description: ""
          items:
            $ref: "#/components/schemas/localized-message"
    size:
      type: object
      properties:
        id:
          type: string
          example: N
        description:
          type: array
          example:
            - language: en
              description: ""
            - language: it
              description: ""
          items:
            $ref: "#/components/schemas/localized-message"
    commodity-code:
      type: object
      properties:
        id:
          type: string
          example: "41032000"
        description:
          type: array
          example:
            - language: en
              description: Skin, reptiles
            - language: it
              description: Cuoi/Pelli di rettili
          items:
            $ref: "#/components/schemas/localized-message"
    packaging-type:
      type: object
      properties:
        id:
          type: string
          example: Z003
        description:
          type: array
          example:
            - language: en
              description: Hang in Bag
            - language: it
              description: Appeso in sacca
          items:
            $ref: "#/components/schemas/localized-message"
    range-name:
      type: object
      properties:
        id:
          type: string
          example: ""
        description:
          type: array
          example:
            - language: en
              description: range name english
            - language: it
              description: range name italian
          items:
            $ref: "#/components/schemas/localized-message"
    capsule-special-projects:
      type: object
      properties:
        id:
          type: string
          example: ""
        description:
          type: array
          example:
            - language: en
              description: Special Project
            - language: it
              description: Progetto speciale
          items:
            $ref: "#/components/schemas/localized-message"
    luxury-article:
      type: object
      properties:
        id:
          type: string
          example: ""
        description:
          type: array
          example:
            - language: en
              description: Luxory
            - language: it
              description: Lusso
          items:
            $ref: "#/components/schemas/localized-message"
    composition:
      type: object
      properties:
        description:
          type: array
          example:
            - language: en
              description: 80% wool, 17% polyester, 2% cotton, 1% plastic
            - language: it
              description: 80% lana, 17% polyester, 2% cotone, 1% materiale plastico
          items:
            $ref: "#/components/schemas/localized-message"
    item:
      type: object
      required:
        - sku
      properties:
        sku:
          type: string
          example: XYZ010XOI69 00102N
        generic-article:
          type: string
          example: XYZ010XOI69 001
        active-season:
          $ref: "#/components/schemas/season"
        creation-season:
          $ref: "#/components/schemas/season"
        style:
          $ref: "#/components/schemas/style"
        fabric:
          $ref: "#/components/schemas/fabric"
        color:
          $ref: "#/components/schemas/color"
        drop:
          $ref: "#/components/schemas/drop"
        variant:
          type: string
          example: ""
        variant-type:
          type: string
          example: ""
        size:
          $ref: "#/components/schemas/size"
        style-fabric-description:
          type: array
          example:
            - language: en
              description: SNK COW SUEDE+CALF V
            - language: it
              description: Vitello V
          items:
            $ref: "#/components/schemas/localized-message"
        article-description:
          type: array
          example:
            - language: en
              description: XYZ010 XOI69 A553 SNK COW SUEDE+CALF V
            - language: it
              description: XYZ010 XOI69 A553 Vitello V
          items:
            $ref: "#/components/schemas/localized-message"
        barcodes:
          type: array
          items:
            $ref: "#/components/schemas/barcode"
        division:
          $ref: "#/components/schemas/division"
        collection:
          $ref: "#/components/schemas/collection"
        theme:
          $ref: "#/components/schemas/theme"
        product:
          $ref: "#/components/schemas/product"
        product-type:
          $ref: "#/components/schemas/product-type"
        product-kind:
          $ref: "#/components/schemas/product-kind"
        merchandise-category:
          $ref: "#/components/schemas/merchandise-category"
        merchandise-group:
          $ref: "#/components/schemas/merchandise-group"
        category:
          $ref: "#/components/schemas/category"
        brand:
          $ref: "#/components/schemas/brand"
        madein:
          type: array
          items:
            $ref: "#/components/schemas/madein"
        fashion-grade:
          $ref: "#/components/schemas/seasonality"
        gender:
          $ref: "#/components/schemas/gender"
        rfid-enabled:
          type: boolean
          default: false
        cites:
          $ref: "#/components/schemas/cites"
        underline:
          $ref: "#/components/schemas/underline"
        commodity-code:
          $ref: "#/components/schemas/commodity-code"
        packaging-type:
          $ref: "#/components/schemas/packaging-type"
        range-name:
          $ref: "#/components/schemas/range-name"
        capsule-special-projects:
          $ref: "#/components/schemas/capsule-special-projects"
        luxury-article:
          $ref: "#/components/schemas/luxury-article"
        status:
          $ref: "#/components/schemas/item-status"
        creation-date:
          type: string
          format: date-time
        last-change-date:
          type: string
          format: date-time
        composition:
          $ref: "#/components/schemas/composition"
