swagger: "2.0"
info:
  description: "Item Master MVP"
  version: "1.0.0"
  title: "Product Catalog"
  termsOfService: "http://api.giorgioarmani.it/terms/"
  contact:
    email: "apiteam@giorgioarmani.it"
  license:
    name: "XXXX"
    url: "http://api.giorgioarmani.it/licenses/LICENSE-API.html"
host: "api.giorgioarmani.it"
basePath: "/v1"
tags:
- name: "item-master"
  description: "Armani Pproduct Catalog"
  externalDocs:
    description: "Find out more"
    url: "http://api.giorgioarmani.it/docs"
schemes:
- "https"
#- "http"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
paths:
  /items:
    get:
      tags:
      - "item"
      summary: "Return all Items for a given Year/Season"
      description: "Return active items"
      operationId: ""
      produces:
      - "application/json"
      - "application/xml"
      security:
      - api_key: []
      parameters:
      - name: "year"
        in: "query"
        description: "Year values that need to be considered for filter"
        required: true
        type: "array"
        items:
          type: "string"
          default: "2022"
        collectionFormat: "multi"
      - name: "season"
        in: "query"
        description: "Season values that need to be considered for filter"
        required: true
        type: "array"
        items:
          type: "string"
          default: "SS"
        collectionFormat: "multi"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/item"
        "400":
          description: "Invalid status value"

definitions:
  # PRODUCT
  product:  
    type: "object"
    properties:
      id:
        type: "string"
        example: "629"
      description:
        type: "string"
        example: "SNEAKERS"
    xml:
      name: "Product"
  # PRODUCT TYPE
  product-type:  
    type: "object"
    properties:
      id:
        type: "string"
        example: "40"
      description:
        type: "string"
        example: "LEATHER"
    xml:
      name: "Product Type"
  # MERCHANDISE CATEGORY
  merchandise-category:  
    type: "object"
    properties:
      id:
        type: "string"
      description:
        type: "string"
    xml:
      name: "Merchandise Category"
  # MERCHANDISE GROUP
  merchandise-group:
    type: "object"
    properties:
      id:
        type: "string"
      description:
        type: "string"
    xml:
      name: "Merchandise Group"
  # CATEGORY 
  category:
    type: "object"
    properties:
      id:
        type: "string"
      description:
        type: "string"
    xml:
      name: "Category"
  # BRAND 
  brand:
    type: "object"
    properties:
      id:
        type: "string"
      description:
        type: "string"
    xml:
      name: "Brand"
  # SEASONALITY
  seasonality:
    type: "string"
    enum:
      - "seasonal"
      - "continuous"
      - "repurposed"
    xml:
      name: "Seasonality"
  # GENDER
  gender:
    type: "string"
    description: "Gender"
    enum:
      - "man"
      - "woman"
      - "unisex"
      - "boy"
      - "girl"
    xml:
      name: "Gender"
  # STATUS
  item-status:
    type: "object"
    description: "Item Status"
    properties:
      status:
        type: "string"
        enum:
          - "active"
          - "cancelled"
      starting-date:
        type: "string"
        format: "date-time"
    xml:
      name: "Item Status"
  # BARCODES
  barcode:
    type: "object"
    description: "barcodes"
    properties:
      barcode: 
        type: "integer"
        example: "8054804724299"
      barcode-type: 
        type: "string"
        example: "GTIN13"
      main:
        type: "boolean"
        default: "false"
  # SEASON
  season-code:
    type: "object"
    description: "Season Code Description"
    properties:
      code: 
        type: "integer"
        example: "30"
      description:
        enum:
          - "Spring/Summer"
          - "Fall/Winter"
  # MADE-IN
  madein:
    type: "object"
    description: "Item Master madein, it might be different from production made-in"
    properties:
      id: 
        type: "string"
        example: "ITA"
      description:
        type: "string"
        example: "Italia"
  # DIVISION
  division:
    type: "object"
    description: "Business Division"
    properties:
      id:
        type: "string"
        example: "JB"
      description:
        type: "string"
        example: "Emporio Armani Boy"
  # COLLECTION
  collection:
    type: "object"
    description: "Collection"
    properties:
      id:
        type: "string"
        example: "JB"
      description:
        type: "string"
        example: "EA Boy"
  # THEME
  theme:
    type: "object"
    description: "Theme"
    properties:
      id:
        type: "string"
        example: "28"
      description:
        type: "string"
        example: "Ext.2 Dl.8"
  # CITES
  cites:
    type: "object"
    description: "Washington Declaration"
    properties:
      id:
        type: "integer"
        format: "int32"
        example: "4"
      description:
        type: "string"
        example: "Mother of pearl"
      
  # ITEM -------------------------------            
  item:
    type: "object"
    required:
    - "sku"
    properties:
      sku:
        type: "string"
        example: "XYZ010XOI69 00102N"
      active-season-year:
        type: "integer"
        format: "int32"
        example: "2022"
      active-season-code:
        $ref: "#/definitions/season-code"
      creation-season-year:
        type: "integer"
        format: "int32"
        example: "2019"
      creation-season-code:
        $ref: "#/definitions/season-code"
      style:
        type: "string"
        example: "XYZ010"
      fabric:
        type: "string"
        example: "XOI69"
      color:
        type: "string"
        example: "A553"
      barcodes:
        type: "array"
        items:
          $ref: "#/definitions/barcode"
      division:
        $ref: "#/definitions/division"
      collection:
        $ref: "#/definitions/collection"
      theme:
        $ref: "#/definitions/theme"
      product:
        $ref: "#/definitions/product"
      product-type:
        $ref: "#/definitions/product-type"
      merchandise-category:
        $ref: "#/definitions/merchandise-category"
      merchandise-group:
        $ref: "#/definitions/merchandise-group"
      category:
        $ref: "#/definitions/category"
      brand:
        $ref: "#/definitions/brand"
      madein:
        $ref: "#/definitions/madein"
      fashion-grade:
        $ref: "#/definitions/seasonality"
      gender:
        $ref: "#/definitions/gender"
      rfid-enabled:
        type: "boolean"
        default: false
      cites:
        $ref: "#/definitions/cites"
      status:
        $ref: "#/definitions/item-status"
      creation-date:
        type: "string"
        format: "date-time"
      last-change-date:
        type: "string"
        format: "date-time"
        
    xml:
      name: "Item"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"