openapi: 3.0.0
info:
  title: Item Master
  description: Giorgio Armani Item Master
  version: "1.0.0"
servers:
  - url: '{protocol}://{environment}.armani.it/v1'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      environment:
        default: api    # Production server
        enum:
          - api      # Production server
          - apidev   # Development server
          - apitst   # Test server
paths:
  /item:
    get:
      summary: Returns active items
      description: Returns active items
      operationId: ""
      parameters:
        - name: season-creation-id
          in: query
          description: Season-creation values that need to be considered for filter
          required: false
          explode: true
          schema:
            type: string
            example: "FW22"
        - name: brand-id
          in: query
          description: brand code
          required: false
          explode: true
          schema:
            type: string
            example: "EA"
        - name: category-id
          in: query
          description: category code
          required: false
          explode: true
          schema:
            type: string
            example: "10"
        - name: collection-id
          in: query
          description: collection code
          required: false
          explode: true
          schema:
            type: string
            example: ""
        - name: division-id
          in: query
          description: division code
          required: false
          explode: true
          schema:
            type: string
            example: ""
        - name: seasonality-id
          in: query
          description: seasonality code
          required: false
          explode: true
          schema:
            type: string
            example: ""
        - name: merchandise-category-id
          in: query
          description: merchandise category code
          required: false
          explode: true
          schema:
            type: string
        - name: product-id
          in: query
          description: product code
          required: false
          explode: true
          schema:
            type: string
        - name: model-id
          in: query
          description: model code
          required: false
          explode: true
          schema:
            type: string
        - name: fabric-id
          in: query
          description: fabric code
          required: false
          explode: true
          schema:
            type: string
        - name: color-id
          in: query
          description: color code
          required: false
          explode: true
          schema:
            type: string
        - name: gender-id
          in: query
          description: gender
          required: false
          explode: true
          schema:
            type: string
        - name: item-category-id
          in: query
          description: item-category
          required: false
          explode: true
          schema:
            type: string

        - $ref: "../common/parameter/date-range.yaml#/parameters/creation-date-start"
        - $ref: "../common/parameter/date-range.yaml#/parameters/creation-date-end"
        - $ref: "../common/parameter/date-range.yaml#/parameters/last-change-date-start"
        - $ref: "../common/parameter/date-range.yaml#/parameters/last-change-date-end"
        - $ref: "../common/parameter/pagination.yaml#/parameters/limit"
        - $ref: "../common/parameter/pagination.yaml#/parameters/offset"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/list"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"

  /item/{item-id}:
    get:
      summary: Returns active item by {item-id}
      description: Returns active item by {item-id}
      operationId: ""
      parameters:
        - name: item-id
          in: path
          description: item-id (can be both sku or generic-article)
          required: true
          explode: true
          schema:
            type: array
            items:
              type: string
              example: "XYZ010XOI69 001"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "item.yaml#/components/schemas/item"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"


security:
  - api-key-auth: []

components:

  securitySchemes:
    api-key-auth:
      type: apiKey
      in: header
      name: X-Gateway-APIKey

  schemas:

    list:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "item.yaml#/components/schemas/item"
