openapi: "3.0.0"
info:
  title: Digital Assets
  description: Digital content
  version: "1.0.0"
servers:
  - url: '{protocol}://{environment}.armani.it/v1'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      environment:
        default: api    # Production server
        enum:
          - api      # Production server
          - apidev   # Development server
          - apitst   # Test server
paths:
  /digital-assets:
    get:
      summary: Return urls to images and video for specified item-id
      description: Return urls to images and video for specified item-id
      operationId: ''
      parameters:
        - name: item-id
          in: query
          description: item-id can be generica item or sku
          required: true
          explode: true
          schema:
            type: string
            default: "XYZ010XOI69 001"
        - name: barcode
          in: query
          description: barcode
          required: false
          explode: true
          schema:
            type: string
            default: "800012927333"
        - name: asset-type
          in: query
          description: type of assets, images, e-commerce,video, 3d, etc...
          required: false
          explode: true
          schema:
            $ref: "asset-type.yaml#/components/schemas/asset-type"
        - name: content-classification
          in: query
          description: content classification (main,front,side,etc )
          required: false
          schema:
            $ref: "content-classification.yaml#/components/schemas/content"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/digital-assets"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"

security:
  - api-key-auth: []

components:

  securitySchemes:
    api-key-auth:
      type: apiKey
      in: header              # can be "header", "query" or "cookie"
      name: X-Gateway-APIKey  # name of the header, query parameter or cookie

  schemas:
    digital-assets:
      type: object
      properties:
        item-id:
          type: string
          example: XYZ010XOI69 001
        href:
          type: string
          format: uri
          example: "https://api.armani.it/v1/digital-assets/XYZ010XOI69 001"
        assets:
          type: array
          items:
            $ref: "assets.yaml#/components/schemas/assets"
