openapi: "3.0.0"
info:
  title: Barcode Allocate
  description: procedure to allocate a new barcode for a given SKU
  version: "1.0.0"
servers:
  - url: '{protocol}://{environment}.armani.it/v1'
    variables:
      protocol:
        enum:
          - https
        default: https
      environment:
        default: api    # Production server
        enum:
          - api      # Production server
          - apidev   # Development server
          - apitst   # Test server
paths:
  /barcode/allocate:
    post:
      summary: Allocate a new barcode for a given SKU
      description: 'Allocate a new barcode for the given SKU'
      parameters:
        - name: item-id
          in: query
          description: item-id (must be a sku)
          required: false
          explode: true
          schema:
            type: string
            default: "XYZ010XOI69 00102N"
        - name: barcode-type
          in: query
          description: barcode type (specify the barcode type, ex. gtin13, atin13, upc, etc...)
          required: false
          explode: true
          schema:
            $ref: "barcode-type.yaml#/components/schemas/barcode-type"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "barcode.yaml#/components/schemas/barcode"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"

security:
  - api-key-auth: []

components:

  securitySchemes:
    api-key-auth:
      type: apiKey
      in: header              # can be "header", "query" or "cookie"
      name: X-Gateway-APIKey  # name of the header, query parameter or cookie
