{
  "swagger": "2.0",
  "info": {
    "description": "API documentation",
    "version": "1.0",
    "title": "Giorgio Armani APIs",
    "termsOfService": "http://api.armani.it/terms/",
    "contact": {
      "email": "enterprise.architect@giorgioarmani.it"
    },
    "license": {
      "name": "",
      "url": ""
    }
  },
  "host": "api.armani.it",
  "basePath": "/v1",
  "tags": [{
    "name": "item-master",
    "description": "Item master",
    "externalDocs": {
      "description": "Find out more",
      "url": "../item-master/item-master.yaml"
    }
  }, {
    "name": "store",
    "description": "Access to Petstore orders"
  }, {
    "name": "user",
    "description": "Operations about user",
    "externalDocs": {
      "description": "Find out more about our store",
      "url": "http://swagger.io"
    }
  }],
  "schemes": ["https"],
  "externalDocs": {
    "description": "Find out more about Swagger",
    "url": "http://swagger.io"
  }
}