openapi: "3.0.0"
info:
  title: Stock
  description: Store Stock
  version: "1.0.0"
servers:
  - url: '{protocol}://{environment}.armani.it/v1'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      environment:
        default: api    # Production server
        enum:
          - api      # Production server
          - apidev   # Development server
          - apitst   # Test server
paths:
  /stock/{barcode}:
    get:
      summary: Return the specified barcode
      description: Return stock availability for given barcode
      operationId: ''
      parameters:
        - name: barcode
          in: path
          description: barcode
          required: true
          explode: true
          schema:
            type: string
            example: "8054804724299"
        - name: retail-store-id
          in: query
          description: store id
          required: true
          schema:
            type: string
            example: "4SCW"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/stock"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"

  /stock:
    get:
      summary: Return all stock avalability
      description: 'Return stock availability for a given store-id, pagination with limit&offset'
      operationId: ''
      parameters:
        - name: retail-store-id
          in: query
          description: retail-store-id
          required: true
          explode: true
          schema:
            type: string
            example: "4S09"
        - name: item-id
          in: query
          description: item-id (sku)
          required: false
          schema:
            type: string
            example: "XD1200393718 001LDU3"
        - name: stock-mode
          in: query
          description: 'Returns positive quantities only or also zero quantities'
          required: false
          schema:
            type: string
            enum:
              - positive
              - total
            default: total
        - $ref: "../common/parameter/pagination.yaml#/parameters/limit"
        - $ref: "../common/parameter/pagination.yaml#/parameters/offset"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/list"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"

security:
  - api-key-auth: []

components:

  securitySchemes:
    api-key-auth:
      type: apiKey
      in: header              # can be "header", "query" or "cookie"
      name: X-Gateway-APIKey  # name of the header, query parameter or cookie

  schemas:
    stock:
      type: object
      properties:
        retail-store-id:
          $ref: "../store/store.yaml#/components/schemas/store"
          example:
            id: "4S09"
            href: "https://api.armani.it/v1/store/4S09"
        barcode:
          $ref: "../barcode/season.yaml#/components/schemas/barcode"
        storage:
          type: array
          items:
            $ref: "./stock-item.yaml#/components/schemas/stock-item"
        unitary-cost:
          description: moving average price (unit)
          $ref: "../common/money.yaml#/components/schemas/money"
        consignment:
          $ref: "./consignment.yaml#/components/schemas/consignment"
        last-change-date:
          $ref: "../common/last-change-date.yaml#/components/schemas/last-change-date"


    list:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/stock"

