openapi: "3.0.0"
info:
  title: Gender
  description: Gender
  version: "1.0.0"
servers:
  - url: '{protocol}://{environment}.armani.it/v1'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      environment:
        default: api    # Production server
        enum:
          - api      # Production server
          - apidev   # Development server
          - apitst   # Test server
paths:
  /gender/{id}:
    get:
      summary: Return gender description
      description: Return gender description
      operationId: ''
      parameters:
        - name: id
          in: query
          description: gender id
          required: true
          explode: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/gender"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"

  /genders:
    get:
      summary: Return list of gender
      description: Return list of gender
      operationId: ''
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/list"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"


security:
  - api-key-auth: []

components:

  securitySchemes:
    api-key-auth:
      type: apiKey
      in: header              # can be "header", "query" or "cookie"
      name: X-Gateway-APIKey  # name of the header, query parameter or cookie

  schemas:
    gender:
      $ref : "../common/gender.yaml#/components/schemas/gender"

      example:
        id: "60"
        href: "https://api.armani.it/v1/gender/60"
        description:
          - language: en
            description: WOMAN

    list:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/gender"

      example:
        items:
          - id: "60"
            href: "https://api.armani.it/v1/gender/60"
            description:
              - language: en
                description: WOMAN
          - id: "30"
            href: "https://api.armani.it/v1/gender/30"
            description:
              - language: en
                description: MAN
          - id: "33"
            href: "https://api.armani.it/v1/gender/33"
            description:
              - language: en
                description: BOY