openapi: "3.0.0"
info:
  title: Business Partner
  description: Giorgio Armani Business Partner
  version: "1.0.0"
servers:
  - url: '{protocol}://{environment}.armani.it/v1'
    variables:
      protocol:
        enum:
          - https
        default: https
      environment:
        default: api    # Production server
        enum:
          - api      # Production server
          - apidev   # Development server
          - apitst   # Test server
paths:
  /business-partner/{business-partner-id}:
    get:
      summary: Return the specified Business Partner
      description: Returns Business Partner
      parameters:
        - name: business-partner-id
          in: path
          description: business-partner-id
          required: true
          explode: true
          schema:
            type: string
            default: "9FA1.01"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/business-partner"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"

  /business-partners:
    get:
      summary: Return all business-partners
      description: 'Return all business-partners'
      parameters:
        - name: id
          in: query
          description: business-partner id
          required: false
          explode: true
          schema:
            type: string
            example: "AFH8.00"
        - name: business-partner-type
          in: query
          description: business-partner-type
          required: false
          explode: true
          schema:
            type: string
            example: person
        - name: gender
          in: query
          description: gender
          required: false
          explode: true
          schema:
            type: string
        - name: firstname
          in: query
          description: firstname
          required: false
          explode: true
          schema:
            type: string
        - name: lastname
          in: query
          description: lastname
          required: false
          explode: true
          schema:
            type: string
        - name: company-name
          in: query
          description: company-name
          required: false
          explode: true
          schema:
            type: string
        - name: nationality
          in: query
          description: nationality
          required: false
          explode: true
          schema:
            type: string
        - name: city
          in: query
          description: city
          required: false
          explode: true
          schema:
            type: string
            example: Tel Aviv
        - name: province
          in: query
          description: province
          required: false
          explode: true
          schema:
            type: string
        - name: region
          in: query
          description: region
          required: false
          explode: true
          schema:
            type: string
        - name: country
          in: query
          description: country
          required: false
          explode: true
          schema:
            type: string
        - name: contact-type
          in: query
          description: contact-type
          required: false
          explode: true
          schema:
            type: string
            example: email
        - name: contact-id
          in: query
          description: contact-id
          required: false
          explode: true
          schema:
            type: string
            example: a.sfolcini@gmail.com
        - name: status
          in: query
          description: status
          required: false
          explode: true
          schema:
            type: string
            example: cancelled
        - name: gln-code
          in: query
          description: GLN code
          required: false
          explode: true
          schema:
            type: string
            example: 1234567890123
        - name: document-id
          in: query
          description: state
          required: false
          explode: true
          schema:
            type: string
        - name: document-type
          in: query
          description: state
          required: false
          explode: true
          schema:
            type: string
            example: sdi

        - $ref: "../common/parameter/date-range.yaml#/parameters/creation-date-start"
        - $ref: "../common/parameter/date-range.yaml#/parameters/creation-date-end"
        - $ref: "../common/parameter/date-range.yaml#/parameters/last-change-date-start"
        - $ref: "../common/parameter/date-range.yaml#/parameters/last-change-date-end"
        - $ref: "../common/parameter/pagination.yaml#/parameters/limit"
        - $ref: "../common/parameter/pagination.yaml#/parameters/offset"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/list"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"

security:
  - api-key-auth: []

components:

  securitySchemes:
    api-key-auth:
      type: apiKey
      in: header              # can be "header", "query" or "cookie"
      name: X-Gateway-APIKey  # name of the header, query parameter or cookie

  schemas:

    status:
      $ref: "../common/status.yaml#/components/schemas/status"
      example: active

    relationships:
      type: array
      items:
          type: object
          properties:
            relation-type:
              type: string
            business-partner:
              type: string
            issue-date:
              type: string
              format: date-time
            expire-date:
              type: string
              format: date-time

    business-partner-main:
      type: object
      properties:
        id:
          type: string
        href:
          type: string
          format: url
    gln-code:
      type: string
    notes:
      type: string
    creation-date:
      type: string
      format: date-time
      example: "2022-03-05T00:00:00.000Z"
    last-change-date:
      type: string
      format: date-time
      example: "2022-03-05T00:00:00.000Z"
    registration-employee:
      $ref: "../employee/employee.yaml#/components/schemas/employee"
    registration-store:
      $ref: "../store/store.yaml#/components/schemas/store"


    communication-languages:
      type: array
      items:
        $ref: "../common/language.yaml#/components/schemas/language"


    business-partners:
      anyOf:
        - $ref: "../common/person.yaml#/components/schemas/person"
        - $ref: "../employee/employee.yaml#/components/schemas/employee"
        - $ref: "../common/company.yaml#/components/schemas/company"
        - $ref: "business-partner-type.yaml#/components/schemas/business-partner-type"
        - $ref: "#/components/schemas/communication-languages"
        - $ref: "#/components/schemas/business-partner-main"
        - $ref: "#/components/schemas/gln-code"
        - $ref: "#/components/schemas/notes"
        - $ref: "#/components/schemas/status"
        - $ref: "#/components/schemas/creation-date"
        - $ref: "#/components/schemas/last-change-date"

      example:
        business-partner-type: person
        id: "9PSN.00"
        href: "https://api.armani.it/v1/business-partner/9PSN.00"
        business-partner-main:
          id: "9PSN.00"
          href: "https://api.armani.it/v1/business-partner/9PSN.00"
        gender: male
        birthday: "1976-03-05T00:00:00.000Z"
        firstname: Alberto
        localized_firstname:
          language: "he"
          description: "אלברטו"
        middlename: Ariel
        localized_middlename:
          language: "he"
          description: "אריאל"
        lastname: Sfolcini
        localized_lastname:
          language: "he"
          description: "ספולצ'יני"
        gln-code: "81726373331"
        contacts:
          - contact-id: "+393392840643"
            contact-type: mobile
            priority: main
            authorization: denied
            status: active
          - contact-id: "a.sfolcini@gmail.com"
            contact-type: email
            priority: main
            authorization: authorized
            status: active
        addresses:
          - address-type: residence
            street: via Amerigo Vespucci
            street-number: 31
            zip-code: 20063
            contacts:
              - contact-id: "+39029515651"
                contact-type: landline
                priority: main
                authorization: denied
                status: active
            city:
              id: Milano
              href: "https://api.armani.it/v1/city/Milano"
            province:
              id: MILANO
              href: "https://api.armani.it/v1/province/MILANO"
            region:
              id: LOM
              href: "https://api.armani.it/v1/region/LOM"
            country:
              id: IT
              href: "https://api.armani.it/v1/country/IT"
            timezone:
              id: "CET"
              href: "https://api.armani.it/v1/timezone/CET"
          - address-type: office
            street: via Bergognone
            street-number: 46
            zip-code: 20121
            contacts:
              - contact-id: "+390283106505"
                contact-type: landline
                priority: main
                authorization: authorized
                status: active
              - contact-id: "+390283106"
                contact-type: contact-center
                priority: secondary
                authorization: authorized
                status: active
            city:
              id: Milano
              href: "https://api.armani.it/v1/city/Milano"
            province:
              id: MILANO
              href: "https://api.armani.it/v1/province/MILANO"
            region:
              id: LOM
              href: "https://api.armani.it/v1/region/LOM"
            country:
              id: IT
              href: "https://api.armani.it/v1/country/IT"
          - address-type: other
            street: Ben Yahuda St
            city:
              id: TLV
              href: "https://api.armani.it/v1/city/TLV"
            country:
              id: IL
              href: "https://api.armani.it/v1/country/IL"
            timezone:
              id: "GMT+3"
              href: "https://api.armani.it/v1/timezone/GMT+3"
        communication-languages:
          - language: it
            description:
              language: it
              description: Italiano
          - language: en
            description:
              language: it
              description: Inglese
        notes: "This is a simple note field"
        documents:
          - id: "IT03722500265"
            document-type: vat-registration-number
          - id: "03722500265"
            document-type: vat-registration-number2
          - id: "RSSMNL70D02C957Z"
            document-type: fiscal-code
          - id: "123456"
            document-type: sdi
        relationships:
          - relation-type:
              id: "Z0050"
              href: "https://api.armani.it/v1/relation-type/Z0050"
            business-partner:
              id: "GA01.00"
              href: "https://api.armani.it/v1/customer/GA01.00"
            issue-date: "2006-02-13T00:00:00.000Z"
            expire-date: "9999-12-31T00:00:00.000Z"
          - relation-type:
              id: "Z0050"
              href: "https://api.armani.it/v1/relation-type/Z0050"
            business-partner:
              id: "GAO1.00"
              href: "https://api.armani.it/v1/customer/GAO1.00"
            issue-date: "2006-02-13T00:00:00.000Z"
            expire-date: "9999-12-31T00:00:00.000Z"
        status: "active"
        creation-date: "2022-03-05T00:00:00.000Z"
        last-change-date: "2022-03-05T00:00:00.000Z"



    list:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/vendor"

