openapi: "3.0.0"
info:
  title: Pricelist
  description: Pricelist
  version: "1.0.0"
servers:
  - url: '{protocol}://{environment}.giorgioarmani.it/v1'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      environment:
        default: api    # Production server
        enum:
          - api      # Production server
          - apidev   # Development server
          - apitst   # Test server
paths:
  /pricelist/{pricelist}:
    get:
      summary: Return the specified pricelist
      description: Return specific pricelist
      operationId: ''
      parameters:
        - name: pricelist
          in: path
          description: pricelist code
          required: true
          explode: true
          schema:
            type: string
            example: "ITR1"
        - name: sales-organization
          in: query
          description: sales-organization
          required: true
          schema:
            type: string
            example: "GA01"
        - name: season-id
          in: query
          description: "season, can be multiple season-id=FW22,FW21,FW20"
          required: false
          explode: false
          schema:
            type: string
            example: "FW22"
        - name: status
          in: query
          description: "filter for active or cancelled prices"
          required: false
          schema:
            type: string
            enum:
              - active
              - cancelled
            default: "active"
        - name: barcode
          in: query
          description: barcode
          required: false
          schema:
            type: string
            example: "8054804724299"
        - name: item-id
          in: query
          description: item-id
          required: false
          schema:
            type: string
            example: "XYZ010XOI69 00102"
        - $ref: "../common/parameter/pagination.yaml#/parameters/limit"
        - $ref: "../common/parameter/pagination.yaml#/parameters/offset"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/pricelist"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"

security:
  - api-key-auth: []

components:

  securitySchemes:
    api-key-auth:
      type: apiKey
      in: header              # can be "header", "query" or "cookie"
      name: X-Gateway-APIKey  # name of the header, query parameter or cookie

  schemas:
    pricelist:
      type: object
      properties:
        sale-organization:
          $ref: "../common/sale-organization.yaml#/components/schemas/sale-organization"
        pricelist:
          type: object
          properties:
            id:
              type: string
              example: "ITR1"
            description:
              type: array
              items:
                $ref: "../common/localized-message.yaml#/components/schemas/localized-message"
        price-item:
          $ref: "price-item.yaml#/components/schemas/price-item"