openapi: "3.0.0"
info:
  title: Forwarding Agent
  description: Forwarding Agent
  version: "1.0.0"
servers:
  - url: '{protocol}://{environment}.armani.it/v1'
    variables:
      protocol:
        enum:
          - https
        default: https
      environment:
        default: api    # Production server
        enum:
          - api      # Production server
          - apidev   # Development server
          - apitst   # Test server
paths:
  /forwarding-agent/{id}:
    get:
      summary: Return Forwardign Agent description
      description: Return Forwardign Agent description
      parameters:
        - name: id
          in: path
          description: gender id
          required: true
          explode: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/forwarding-agent"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"

  /forwarding-agents:
    get:
      summary: Return list of forwarding-agents
      description: Return list of forwarding-agents
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/list"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"


security:
  - api-key-auth: []

components:

  securitySchemes:
    api-key-auth:
      type: apiKey
      in: header              # can be "header", "query" or "cookie"
      name: X-Gateway-APIKey  # name of the header, query parameter or cookie

  schemas:
    forwarding-agent:
      type: object
      properties:
        id:
          type: string
        href:
          type: string
          format: url
        description:
          type: string
        addresses:
          $ref : "../common/address.yaml#/components/schemas/address"

      example:
        id: "BRTMI"
        href: "https://api.armani.it/v1/forwarding-agent/BRTMI"
        description:
          - language: en
            description: BARTOLINI MILANO
        addresses:
          id: "1"
          address-type: legal
          street: "Via degli spedizionieri"
          street-number: "34"
          zip-code: "20100"
          city:
            id: "Milano"
            href: "https://api.armani.it/v1/city/Milano"
          contacts:
            - contact-id: "+39029515651"
              contact-type: landline
              priority: main
              status: active
            - contact-id: "bartolini.legal.milano@spedizionieri.net"
              contact-type: email
              priority: main
              status: active
          province:
            id: "Milano"
          region:
            id: "Lombardia"
          country:
            id: "Italia"




    list:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/forwarding-agent"

