openapi: "3.0.0"
info:
  title: Product-Type
  description: Product-Type
  version: "1.0.0"
servers:
  - url: '{protocol}://{environment}.armani.it/v1'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      environment:
        default: api    # Production server
        enum:
          - api      # Production server
          - apidev   # Development server
          - apitst   # Test server
paths:
  /product-type/{id}:
    get:
      summary: Return product-type description
      description: Return product-type description
      operationId: ''
      parameters:
        - name: id
          in: query
          description: product-type id
          required: true
          explode: true
          schema:
            type: string
            example: "40"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/product-type"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"

  /product-type:
    get:
      summary: Return list of product-types
      description: Return list of products-types
      operationId: ''
      parameters:
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/list"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"


security:
  - api-key-auth: []

components:

  securitySchemes:
    api-key-auth:
      type: apiKey
      in: header              # can be "header", "query" or "cookie"
      name: X-Gateway-APIKey  # name of the header, query parameter or cookie

  schemas:
    product-type:
      $ref : "../common/product-type.yaml#/components/schemas/product-type"

      example:
        id: "40"
        href: "https://api.armani.it/v1/product-type/40"
        description:
          - language: en
            description: LEATHER

    list:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/product-type"

      example:
        items:
          - id: "40"
            href: "https://api.armani.it/v1/product/40"
            description:
              - language: en
                description: LEATHER
          - id: "55"
            href: "https://api.armani.it/v1/product-type/55"
            description:
              - language: en
                description: DENIM
          - id: "10"
            href: "https://api.armani.it/v1/product-type/10"
            description:
              - language: en
                description: WOVEN