components:
  schemas:
    product:
      type: object
      properties:
        id:
          type: string
          example: '629'
        description:
          type: array
          items:
            $ref: './localized-message.yaml#/components/schemas/localized-message'
          example:
            - language: en
              description: SNEAKERS
            - language: it
              description: Scarpe da ginnastica