components:
  schemas:
    product-type:
      type: object
      properties:
        id:
          type: string
          example: '40'
        description:
          type: array
          items:
            $ref: './localized-message.yaml#/components/schemas/localized-message'
          example:
            - language: en
              description: LEATHER
            - language: it
              description: Pelle