openapi: 3.0.0
info:
  title: Transaction
  description: Giorgio Armani transaction
  version: "1.0.0"
servers:
  - url: '{protocol}://{environment}.giorgioarmani.it/v1'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      environment:
        default: api    # Production server
        enum:
          - api      # Production server
          - apidev   # Development server
          - apitst   # Test server
paths:
  /transactions:
    get:
      summary: Returns transactions
      description: Returns transactions
      operationId: ""
      parameters:
        - $ref: "../common/parameter/idempotent-key.yaml#/parameters/idempotent-key"
        - name: retail-store-id
          in: query
          description: Store id
          required: true
          explode: true
          schema:
            type: string
            example: "4S09"
        - name: channel-id
          in: query
          description: "Is transaction born on fixed POS or mobile POS ?"
          required: false
          schema:
            $ref: "./pos-channel-type.yaml#/components/schemas/pos-channel-type"
        - name: transaction-type
          in: query
          description: "Transaction Type ( Sales, EOD,void,goodmvt)"
          required: false
          schema:
            $ref: "./transaction-type.yaml#/components/schemas/transaction-type"
        - name: operator-id
          in: query
          description: Operator Id
          schema:
            type: string
            example: "AY85GT"
        - name: customer-id
          in: query
          description: Customer Id
          schema:
            type: string
            example: "10934402"
        - name: business-range-date
          $ref: "../common/parameter/date-filter.yaml#/parameters/range-date"
        - name: business-start-date
          $ref: "../common/parameter/date-filter.yaml#/parameters/start-date"
        - name: business-end-date
          $ref: "../common/parameter/date-filter.yaml#/parameters/end-date"

        - name: original-transaction-id
          in: query
          description: "Reference to Original Receipt for Transaction Number"
          schema:
            type: string
            example: ""

        - name: fiscal-number
          in: query
          description: "Fiscal number"
          schema:
            type: string
        - name: invoice-number
          in: query
          description: "Invoice number"
          schema:
            type: string

        - $ref: "../common/parameter/pagination.yaml#/parameters/limit"
        - $ref: "../common/parameter/pagination.yaml#/parameters/offset"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/transaction"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"

    post:
      summary: Create a new transaction
      description: Create a new transaction
      operationId: ""
      parameters:
        - $ref: "../common/parameter/idempotent-key.yaml#/parameters/idempotent-key"
        - name: body
          in: body
          required: true
          schema:
              $ref: "#/components/schemas/transaction"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "0004CW019999999"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"


  /transaction/{transaction-id}:
    get:
      summary: Returns a transaction by id
      description: Returns transaction by id
      operationId: ""
      parameters:
        - $ref: "../common/parameter/idempotent-key.yaml#/parameters/idempotent-key"
        - name: transaction-id
          in: path
          description: Season values that need to be considered for filter
          required: true
          explode: true
          schema:
            type: string
            example: "0004CW011063516"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/transaction"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"


security:
  - api-key-auth: []

components:

  securitySchemes:
    api-key-auth:
      type: apiKey
      in: header
      name: X-Gateway-APIKey



  schemas:
    transaction:
      type: object
      properties:
        id:
          type: string
          example: 0004CW011063516
          description: transction id
        transaction-type:
          $ref: "./transaction-type.yaml#/components/schemas/transaction-type"
        workstation-id:
          type: string
          description: POS Number
          example: "1"
        retail-store-id:
          $ref: "../store/store.yaml#/components/schemas/store"
          example:
            id: "4SCW"
            href: "https://api.giorgioarmani.it/v1/store/4SCW"
        channel:
          $ref: "./pos-channel-type.yaml#/components/schemas/pos-channel-type"
          example: "retail-mobile"
        business-date:
          type: string
          format: date-time
          description: Posting Date
        transaction-start:
          type: string
          format: date-time
        transaction-end:
          type: string
          format: date-time
        operator-id:
          $ref: "../employee/employee.yaml#/components/schemas/employee"
          example:
            id: "AY85GT"
            href: "https://api.giorgioarmani.it/v1/employee/AY85GT"
        partner-id:
          $ref: "../customer/customer.yaml#/components/schemas/customer"
          example:
            id: "10934402"
            href: "https://apiarmani.gateway.webmethodscloud.de/gateway/GA_ALL_CAR_CUSTOMER_DATA_IN/1/CustomerSet?$filter=substringof('10934402', Partner)&$format=json"
        original-transaction-id:
          type: string
          description: "Reference to Original Receipt for Transaction Number"
          example: ""
        fiscal-number:
          type: string
          example: 16
        document-type:
          $ref: "./document-type.yaml#/components/schemas/document-type"
        invoice-number:
          type: string
          example: "11820054"
        tax-free-id:
          type: string
          example: "5065910159"
        omni-channel-reason:
          $ref: "./omni-channel-reason.yaml#/components/schemas/omni-channel-reason"
        creation-date:
          $ref: "../common/creation-date.yaml#/components/schemas/creation-date"
        last-change-date:
          $ref: "../common/last-change-date.yaml#/components/schemas/last-change-date"
        transaction-items:
          type: array
          items:
            $ref: "./transaction-item.yaml#/components/schemas/transaction-item"
        tenders:
          type: array
          items:
            $ref: "./tender.yaml#/components/schemas/tender"












