openapi: 3.0.0
info:
  title: Transaction
  description: Giorgio Armani transaction
  version: "1.0.0"
servers:
  - url: '{protocol}://{environment}.giorgioarmani.it/v1'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      environment:
        default: api    # Production server
        enum:
          - api      # Production server
          - apidev   # Development server
          - apitst   # Test server
paths:
  /transactions:
    get:
      summary: Returns transactions
      description: Returns transactions
      operationId: ""
      parameters:
        - name: retail-store-id
          in: query
          description: Store id
          required: true
          explode: true
          schema:
            type: string
            example: "4S09"

        - $ref: "../common/parameter/pagination.yaml#/parameters/limit"
        - $ref: "../common/parameter/pagination.yaml#/parameters/offset"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/transaction"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"


  /transaction/{transaction-id}:
    get:
      summary: Returns a transaction by id
      description: Returns transaction by id
      operationId: ""
      parameters:
        - name: transaction-id
          in: path
          description: Season values that need to be considered for filter
          required: true
          explode: true
          schema:
            type: string
            example: "0004CW011063516"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/transaction"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"

security:
  - api-key-auth: []

components:

  securitySchemes:
    api-key-auth:
      type: apiKey
      in: header
      name: X-Gateway-APIKey





  schemas:
    transaction:
      type: object
      properties:
        id:
          type: string
          example: 0004CW011063516
          description: transction id
        transaction-type:
          $ref: "#/components/schemas/transaction-type"
        workstation-id:
          type: string
          description: POS Number
          example: "1"
        retail-store-id:
          type: string
          description: store id
          example: "4SCW"
        channel:
          $ref: "#/components/schemas/channel-type"
          example: "retail-mobile"
        business-date:
          type: string
          format: date-time
          description: Posting Date
        transaction-start:
          type: string
          format: date-time
        transaction-end:
          type: string
          format: date-time
        operator-id:
          type: string
          example: "AMCE00"
        partner-id:
          type: string
          description: CRM customer
          example: "18834429"
        original-transaction-id:
          type: string
          description: "Reference to Original Receipt for Transaction Number"
          example: ""
        transaction-items:
          type: array
          items:
            $ref: "#/components/schemas/transaction-item"
        tenders:
          type: array
          items:
            $ref: "#/components/schemas/tender"



    # record qualifier 5
    transaction-item:
      type: object
      properties:
          id:
            type: integer
            description: "Sales Item Number"
            example: 1
          retail-type-code:
            type: string
            description: "Sales Item Type"
            example:
          item-id:
            type: string
            description: sku
            example: "XYZ010XOI69 001"
          barcode:
            type: string
            description: ""
            example: "8056861316127"
          quantity:
            type: integer
            description: "Quantity in Sales Unit"
            example: 1
          sales-amount:
            $ref: "../common/money.yaml#/components/schemas/money"
          actual-unit-price:
            $ref: "../common/money.yaml#/components/schemas/money"
          tax:
            $ref: "#/components/schemas/tax"
          discounts:
            type: array
            items:
              $ref: "#/components/schemas/discount"
          commission:
            $ref: "#/components/schemas/commission"




    # record qualifier 13 Tax
    tax:
      type: object
      properties:
        id:
          type: string
          description: "Tax Item id"
          example: "4301"
        description:
          type: string
          description: "Tax Type"
          example: ""
        tax-amount:
          $ref: "../common/money.yaml#/components/schemas/money"
      example:
        id: "4301"
        description: "VAT"
        tax-amount:
          amount: 22
          currency: "EUR"


    # record qualifier 11 Discount
    discount:
      type: object
      properties:
        id:
          type: string
          description: "Discount ID"
        description:
          type: string
          description: "Discount Type Description"
        reduction-amount:
          $ref: "../common/money.yaml#/components/schemas/money"
        offer-id:
          type: string
          description: "Offer ID"
          example: ""
      example:
        id: "84"
        description: "Employee Discount"
        reduction-amount:
          amount: 50.05
          currency: "EUR"
        offer-id: "Employees"


    # record qualifier 15 Commission
    commission:
      type: object
      properties:
        employee-id:
          type: string
          description: "Salesperson ID"
          example: "AY34HQ"

    # record qualifier 21 Tender
    tender:
      type: object
      properties:
        id:
          type: string
          description: "Tender ID"
        description:
          type: string
          description: "Tender Description"
        amount:
          $ref: "../common/money.yaml#/components/schemas/money"
      example:
        id: "148"
        description: "VISA POS"
        amount:
          amount: "71.9"
          currency: "EUR"



    transaction-type:
      type: string
      enum:
        - sales
        - good-movement
        - end-of-day
        - void


    channel-type:
      type: string
      description: channel
      enum:
        - retail-mobile
        - retail-tablet