openapi: 3.0.0
info:
  title: Transaction
  description: Giorgio Armani transaction
  version: "1.0.0"
servers:
  - url: '{protocol}://{environment}.giorgioarmani.it/v1'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      environment:
        default: api    # Production server
        enum:
          - api      # Production server
          - apidev   # Development server
          - apitst   # Test server
paths:
  /transactions:
    get:
      summary: Returns transactions
      description: Returns transactions
      operationId: ""
      parameters:
        - $ref: "../common/parameter/idempotent-key.yaml#/parameters/idempotent-key"
        - name: retail-store-id
          in: query
          description: Store id
          required: true
          explode: true
          schema:
            type: string
            example: "4S09"
        - name: channel-id
          in: query
          description: "Is transaction born on fixed POS or mobile POS ?"
          required: false
          schema:
            $ref: "#/components/schemas/pos-channel-type"
        - name: transaction-type
          in: query
          description: "Transaction Type ( Sales, EOD,void,goodmvt)"
          required: false
          schema:
            $ref: "#/components/schemas/transaction-type"
        - name: operator-id
          in: query
          description: Operator Id
          schema:
            type: string
            example: "AY85GT"
        - name: customer-id
          in: query
          description: Customer Id
          schema:
            type: string
            example: "10934402"
        - name: business-range-date
          $ref: "../common/parameter/date-filter.yaml#/parameters/range-date"
        - name: business-start-date
          $ref: "../common/parameter/date-filter.yaml#/parameters/start-date"
        - name: business-end-date
          $ref: "../common/parameter/date-filter.yaml#/parameters/end-date"

        - name: original-transaction-id
          in: query
          description: "Reference to Original Receipt for Transaction Number"
          schema:
            type: string
            example: ""

        - name: fiscal-number
          in: query
          description: "Fiscal number"
          schema:
            type: string
        - name: invoice-number
          in: query
          description: "Invoice number"
          schema:
            type: string

        - $ref: "../common/parameter/pagination.yaml#/parameters/limit"
        - $ref: "../common/parameter/pagination.yaml#/parameters/offset"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/transaction"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"


  /transaction/{transaction-id}:
    get:
      summary: Returns a transaction by id
      description: Returns transaction by id
      operationId: ""
      parameters:
        - $ref: "../common/parameter/idempotent-key.yaml#/parameters/idempotent-key"
        - name: transaction-id
          in: path
          description: Season values that need to be considered for filter
          required: true
          explode: true
          schema:
            type: string
            example: "0004CW011063516"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/transaction"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"

security:
  - api-key-auth: []

components:

  securitySchemes:
    api-key-auth:
      type: apiKey
      in: header
      name: X-Gateway-APIKey





  schemas:
    transaction:
      type: object
      properties:
        id:
          type: string
          example: 0004CW011063516
          description: transction id
        transaction-type:
          $ref: "#/components/schemas/transaction-type"
        workstation-id:
          type: string
          description: POS Number
          example: "1"
        retail-store-id:
          type: string
          description: store id
          example: "4SCW"
        channel:
          $ref: "#/components/schemas/pos-channel-type"
          example: "retail-mobile"
        business-date:
          type: string
          format: date-time
          description: Posting Date
        transaction-start:
          type: string
          format: date-time
        transaction-end:
          type: string
          format: date-time
        operator-id:
          $ref: "#/components/schemas/employee"
        partner-id:
          $ref: "#/components/schemas/customer"
        original-transaction-id:
          type: string
          description: "Reference to Original Receipt for Transaction Number"
          example: ""
        fiscal-number:
          type: string
          example: 16
        document-type:
          type: object
          properties:
            id:
              type: string
              example: "VI"
            description:
              type: string
              example: "Vat Invoice"
        invoice-number:
          type: string
          example: "11820054"
        tax-free-id:
          type: string
          example: "5065910159"
        omni-channel-reason:
          $ref: "#/components/schemas/omni-channel-reason"
        creation-date:
          $ref: "../common/creation-date.yaml#/components/schemas/creation-date"
        last-change-date:
          $ref: "../common/last-change-date.yaml#/components/schemas/last-change-date"
        transaction-items:
          type: array
          items:
            $ref: "#/components/schemas/transaction-item"
        tenders:
          type: array
          items:
            $ref: "#/components/schemas/tender"



    # record qualifier 5
    transaction-item:
      type: object
      properties:
          id:
            type: integer
            description: "Sales Item Number"
            example: 1
          retail-type-code:
            $ref: "#/components/schemas/retail-type"
          barcode:
            $ref: "../barcode/barcode.yaml#/components/schemas/barcode"
          quantity:
            type: integer
            description: "Quantity in Sales Unit"
            example: 1
          sales-amount:
            $ref: "../common/money.yaml#/components/schemas/money"
          actual-unit-price:
            $ref: "../common/money.yaml#/components/schemas/money"
          tax:
            $ref: "#/components/schemas/tax"
          discounts:
            type: array
            items:
              $ref: "#/components/schemas/discount"
          commission:
            $ref: "#/components/schemas/commission"




    # record qualifier 13 Tax
    tax:
      type: object
      properties:
        id:
          type: string
          description: "Tax Item id"
          example: "4301"
        description:
          type: string
          description: "Tax Type"
          example: ""
        tax-amount:
          $ref: "../common/money.yaml#/components/schemas/money"
        tax-percentage:
          $ref: "../common/unit.yaml#/components/schemas/unit"
      example:
        id: "4301"
        description: "VAT"
        tax-amount:
          amount: 2200
          currency: "EUR"
        tax-percentage:
          value: 22
          unit: "percent"


    # record qualifier 11 Discount
    discount:
      type: object
      properties:
        id:
          type: string
          description: "Discount ID"
        description:
          type: string
          description: "Discount Type Description"
        reduction-amount:
          $ref: "../common/money.yaml#/components/schemas/money"
        reduction-percentage:
          $ref: "../common/unit.yaml#/components/schemas/unit"
        gift-card:
          $ref: "#/components/schemas/gift-card"
        offer-id:
          type: string
          description: "Offer ID"
          example: ""
      example:
        id: "84"
        description: "Employee Discount"
        reduction-amount:
          amount: 5005
          currency: "EUR"
        reduction-percentage:
          value: 40
          unit: "percent"
        gift-card:
          id: "123456ABC"
          card-holder: "Alberto Sfolcini"
          original-amount:
            amount: 10000
            currency: "EUR"
          residual-amount:
            amount: 90000
            currency: "EUR"
        offer-id: "Employees"


    # record qualifier 15 Commission
    commission:
      type: object
      properties:
        employee:
          $ref: "#/components/schemas/employee"


    # record qualifier 21 Tender
    tender:
      type: object
      properties:
        id:
          type: string
          description: "Tender ID"
        description:
          type: string
          description: "Tender Description"
        amount:
          $ref: "../common/money.yaml#/components/schemas/money"
        exchange-rate:
          type: number
          format: decimal
          description: Exchange Rate in caso of currency conversion
        foreign-currency-amount:
          $ref: "../common/money.yaml#/components/schemas/money"
          description: "Exchange rate from transaction to payment currency"

      example:
        id: "148"
        description: "VISA POS"
        amount:
          amount: 71900
          currency: "EUR"
        exchange-rate: 0.88
        foreign-currency-amount:
          amount: 80590
          currency: "USD"


    transaction-type:
      type: string
      enum:
        - sales
        - good-movement
        - end-of-day
        - void

    retail-type:
      type: object
      description: ""
      properties:
        id:
          type: string
          example: "60"
        description:
          type: string
          example: "Sales"


    pos-channel-type:
      type: string
      description: POS channel
      enum:
        - retail-mobile-pos
        - retail-fixed-pos

    # Gift Card object to externalize !!
    gift-card:
      type: object
      properties:
        id:
          type: string
          example: "123456ABC"
        card-holder:
          type: string
        original-amount:
          $ref: "../common/money.yaml#/components/schemas/money"
        residual-amount:
          $ref: "../common/money.yaml#/components/schemas/money"
      example:
        id: "123456ABC"
        card-holder: "Alberto Sfolcini"
        original-amount:
            amount: 10000
            currency: "EUR"
        residual-amount:
          amount: 90000
          currency: "EUR"

    # Control table 5
    document-type:
      type: object
      properties:
        id:
          type: string
          example: "VI"
        description:
          type: string
          example: "Vat Invoice"

    # Control table 6
    omni-channel-reason:
      type: object
      properties:
        id:
          type: string
          example: "ECCR"
        description:
          type: string
          example: "CLICK AND RESERVE"


# esportare Customer ed Employee nelle rispettive API !!





    # Person
    person:
      type: object
      description: A person :-)
      properties:
        id:
          type: string
          description: person id
          required: true
        href:
          type: string
          format: uri
          required: true
        gender:
          type: string
          description: gender
          enum:
            - male
            - female
            - gender-fluid
        birthday:
          type: date-time
          description: date of birth
        firstname:
          type: string
          description: name
        lastname:
          type: string
          description: surname
        addresses:
          type: array
          items:
            $ref: "../common/address.yaml#/components/schemas/address"


    employee:
      anyOf: # Combines the main `Person` schema with `Employee` specific properties
        - $ref: '#/components/schemas/person'
        - type: object
          description: Employee
          properties:
           company:
             type: string
             description: company
      example:
        id: "AY85GT"
        href: "https://api.giorgioarmani.it/v1/employee/AY85GT"
        company: "Giorgio Armani Retail"


    # Customer
    customer:
      anyOf:
        - $ref: '#/components/schemas/person'
      example:
        id: "10934402"
        href: "https://apiarmani.gateway.webmethodscloud.de/gateway/GA_ALL_CAR_CUSTOMER_DATA_IN/1/CustomerSet?$filter=substringof('10934402', Partner)&$format=json"
