openapi: "3.0.0"
info:
  title: Delivery
  description: Delivery, can be inbound or outbound delivery
  version: "1.0.0"
servers:
  - url: '{protocol}://{environment}.armani.it/v1'
    variables:
      protocol:
        enum:
          - https
        default: https
      environment:
        default: api    # Production server
        enum:
          - api      # Production server
          - apidev   # Development server
          - apitst   # Test server
paths:
    /delivery/{id}:
      get:
        summary: Return the given delivery
        description: Return the delivery
        parameters:
          - name: id
            in: path
            description: delivery id
            required: true
            explode: true
            schema:
              type: string
              example: "321272833"
        responses:
          "200":
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/delivery"
          "401":
            description: Unauthorized Error
            content:
              application/json:
                schema:
                  $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
          "default":
            description: Unexpected Error
            content:
              application/json:
                schema:
                  $ref: "../error/error.yaml#/components/schemas/error"

      patch:
        summary: Update the given delivery
        description: Update the delivery
        parameters:
          - name: id
            in: path
            description: delivery id
            required: true
            explode: true
            schema:
              type: string
              example: "321272833"
        responses:
          "200":
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/delivery"
          "401":
            description: Unauthorized Error
            content:
              application/json:
                schema:
                  $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
          "default":
            description: Unexpected Error
            content:
              application/json:
                schema:
                  $ref: "../error/error.yaml#/components/schemas/error"

    /deliveries:
      get:
        summary: Return list of deliveries
        description: Return list of delvieries
        parameters:
          - name: delivery-type
            in: query
            description: delivery type
            required: true
            explode: true
            schema:
              type: string
              enum:
                - inbound
                - outbound
        responses:
          "200":
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/list"
          "401":
            description: Unauthorized Error
            content:
              application/json:
                schema:
                  $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
          "default":
            description: Unexpected Error
            content:
              application/json:
                schema:
                  $ref: "../error/error.yaml#/components/schemas/error"

security:
  - api-key-auth: []

components:

  securitySchemes:
    api-key-auth:
      type: apiKey
      in: header              # can be "header", "query" or "cookie"
      name: X-Gateway-APIKey  # name of the header, query parameter or cookie

  schemas:
    delivery:
      type: object
      properties:
        id:
          type: string
        href:
          type: string
          format: url
        delivery-type:
          $ref: "delivery-type.yaml#/components/schemas/delivery-type"
        ddt-number:
          type: string
        document-date:
          type: string
          format: date-time
        gross-weight:
          $ref: "../common/uom-value.yaml#/components/schemas/uom-value"
        net-weight:
          $ref: "../common/uom-value.yaml#/components/schemas/uom-value"
        volume:
          $ref: "../common/uom-value.yaml#/components/schemas/uom-value"
        total-package-number:
          type: string
        total-quantity:
          type: string
        shipment-number:
          type: string
        invoice-number:
          type: string
        ref-delivery:
          type: string
          description: it can be outbound delivery or inbound delivery depengin on delivery-type
        external-asn-id:
          type: string
        destination-site:
          $ref: "../common/site.yaml#/components/schemas/site"
        sending-site:
          $ref: "../common/site.yaml#/components/schemas/site"
        receiving-point:
          $ref: "../common/site.yaml#/components/schemas/site"
        shipping-point:
          $ref: "../common/site.yaml#/components/schemas/site"
        vendor:
          $ref: "vendor.yaml#/components/schemas/vendor"
        forwarding-agent:
          $ref: "../forwarding-agent/forwarding-agent.yaml#/components/schemas/forwarding-agent"
        expected-receiving-date:
           type: string
           format: date-time
        count-type:
          $ref: "count-type.yaml#/components/schemas/count-type"
        delivery-status:
           type: string
        creation-date:
          $ref: "../common/creation-date.yaml#/components/schemas/creation-date"
        last-change-date:
          $ref: "../common/last-change-date.yaml#/components/schemas/last-change-date"
        delivery-items:
          $ref: "delivery-items.yaml#/components/schemas/delivery-items"

    list:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/delivery"