openapi: "3.0.0"
info:
  title: Delivery
  description: Delivery, can be inbound or outbound delivery dependign on delivery-type, fields must be valorized accordingly.
  version: "1.0.0"
servers:
  - url: '{protocol}://{environment}.armani.it/v1'
    variables:
      protocol:
        enum:
          - https
        default: https
      environment:
        default: api    # Production server
        enum:
          - api      # Production server
          - apidev   # Development server
          - apitst   # Test server
paths:
    /delivery/{id}:
      get:
        summary: Return the given delivery
        description: Return the delivery
        parameters:
          - name: id
            in: path
            description: delivery id
            required: true
            explode: true
            schema:
              type: string
              example: "321272833"
        responses:
          "200":
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/delivery"
          "401":
            description: Unauthorized Error
            content:
              application/json:
                schema:
                  $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
          "default":
            description: Unexpected Error
            content:
              application/json:
                schema:
                  $ref: "../error/error.yaml#/components/schemas/error"

      patch:
        summary: Update the given delivery
        description: Update the delivery
        parameters:
          - name: id
            in: path
            description: delivery id
            required: true
            explode: true
            schema:
              type: string
              example: "321272833"
        responses:
          "200":
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/delivery"
          "401":
            description: Unauthorized Error
            content:
              application/json:
                schema:
                  $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
          "default":
            description: Unexpected Error
            content:
              application/json:
                schema:
                  $ref: "../error/error.yaml#/components/schemas/error"

    /deliveries:
      get:
        summary: Return list of deliveries
        description: Return list of delvieries
        parameters:
          - name: delivery-type
            in: query
            description: delivery type
            required: true
            explode: true
            schema:
              type: string
              enum:
                - inbound
                - outbound
        responses:
          "200":
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/list"
          "401":
            description: Unauthorized Error
            content:
              application/json:
                schema:
                  $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
          "default":
            description: Unexpected Error
            content:
              application/json:
                schema:
                  $ref: "../error/error.yaml#/components/schemas/error"

security:
  - api-key-auth: []

components:

  securitySchemes:
    api-key-auth:
      type: apiKey
      in: header              # can be "header", "query" or "cookie"
      name: X-Gateway-APIKey  # name of the header, query parameter or cookie

  schemas:
    delivery:
      type: object
      properties:
        id:
          type: string
        href:
          type: string
          format: url
        delivery-type:
          $ref: "delivery-type.yaml#/components/schemas/delivery-type"
        ddt-number:
          type: string
        document-date:
          type: string
          format: date-time
        gross-weight:
          $ref: "../common/uom-value.yaml#/components/schemas/uom-value"
        net-weight:
          $ref: "../common/uom-value.yaml#/components/schemas/uom-value"
        volume:
          $ref: "../common/uom-value.yaml#/components/schemas/uom-value"
        total-package-number:
          type: string
        total-quantity:
          type: string
        shipment-number:
          type: string
        invoice-number:
          type: string
        ref-delivery:
          type: string
          description: it can be outbound delivery or inbound delivery depengin on delivery-type
        external-asn-id:
          type: string
        destination-site:
          $ref: "../store/store.yaml#/components/schemas/store"
        sending-site:
          $ref: "../store/store.yaml#/components/schemas/store"
        receiving-point:
          $ref: "../store/store.yaml#/components/schemas/store"
        shipping-point:
          $ref: "../store/store.yaml#/components/schemas/store"
        vendor:
          $ref: "vendor.yaml#/components/schemas/vendor"
        forwarding-agent:
          $ref: "../forwarding-agent/forwarding-agent.yaml#/components/schemas/forwarding-agent"
        expected-receiving-date:
           type: string
           format: date-time
        count-type:
          $ref: "count-type.yaml#/components/schemas/count-type"
        delivery-status:
           type: string
        creation-date:
          $ref: "../common/creation-date.yaml#/components/schemas/creation-date"
        last-change-date:
          $ref: "../common/last-change-date.yaml#/components/schemas/last-change-date"
        delivery-items:
          $ref: "delivery-items.yaml#/components/schemas/delivery-items"

      example:
        id: "3205703283"
        href: "https://api.armani.it/v1/delivery/3205703283"
        delivery-type: "outbound"
        ddt-number: "string"
        document-date: "2022-06-16T13:48:49.858Z"
        gross-weight:
          uom: "kg"
          value: "1.2"
        net-weight:
          uom: "kg"
          value: "1.15"
        volume:
          uom: "cm3"
          value: "256"
        total-package-number: 1
        total-quantity: 8
        shipment-number: "string"
        invoice-number: "string"
        ref-delivery: "string"
        external-asn-id: "string"
        destination-site:
          id: "4SU1"
          href: "https://api.armani.it/v1/site/4SU1"
        sending-site:
          id: "4S09"
          href: "https://api.armani.it/v1/site/4S09"
        receiving-point:
          id: "4SU1"
          href: "https://api.armani.it/v1/site/4SU1"
        shipping-point:
          id: "4S09"
          href: "https://api.armani.it/v1/site/4S09"
        vendor:
          id: "12334"
          href: "https://api.armani.it/v1/vendor/12334"
        forwarding-agent:
          id: "BRTMI"
          href: "https://api.armani.it/v1/forwarding-agent/BRTMI"
        expected-receiving-date: "2022-06-18T13:48:49.858Z"
        count-type": "sku"
        delivery-status: "open"
        creation-date: "2022-06-16T13:48:49.858Z"
        last-change-date: "2022-06-16T13:48:49.858Z"
        delivery-items:
          - id: "1"
            barcode:
              id: "8054804724299"
              item-id: "XYZ010XOI69 00102N"
              item-type: "sku"
              barcode-type: "gtin13"
            delivery-item-status: "open"
            storage-location:
              id: "0001"
              href: "https://api.armani.it/v1/storage-location/0001"
            cites:
              id: 4,
              href: "https://api.armani.it/v1/cites/4"
            packages:
              - id: "415638728"
                barcode:
                  id: "1111222223333344444333332222222"
                  item-type: "package"
                  barcode-type: "sscc"
                quantity: 5
                packaging-type:
                  id: "Z001"
                  href: "https://api.armani.it/v1/packaging-type/Z001"
              - id: "415638729"
                barcode:
                  id: "111122222333334444433333229999999"
                  item-type: "package"
                  barcode-type: "sscc"
                quantity: 3
                packaging-type:
                  id: "Z001"
                  href: "https://api.armani.it/v1/packaging-type/Z001"

    list:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/delivery"