openapi: "3.0.0"
info:
  title: Merchandise Group
  description: Merchandise Group
  version: "1.0.0"
servers:
  - url: '{protocol}://{environment}.armani.it/v1'
    variables:
      protocol:
        enum:
          - https
        default: https
      environment:
        default: api    # Production server
        enum:
          - api      # Production server
          - apidev   # Development server
          - apitst   # Test server
paths:
  /merchandise-group/{id}:
    get:
      summary: Return merchandise-group description
      description: Return merchandise-group description
      parameters:
        - name: id
          in: path
          description: merchandise-group id
          required: true
          explode: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/merchandise-group"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"

  /merchandise-groups:
    get:
      summary: Return list of merchandise-categories
      description: Return list of merchandise-categories
      parameters:
        - $ref: "../common/parameter/pagination.yaml#/parameters/limit"
        - $ref: "../common/parameter/pagination.yaml#/parameters/offset"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/list"
        "401":
          description: Unauthorized Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/unauthorized-error"
        "default":
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "../error/error.yaml#/components/schemas/error"


security:
  - api-key-auth: []

components:

  securitySchemes:
    api-key-auth:
      type: apiKey
      in: header              # can be "header", "query" or "cookie"
      name: X-Gateway-APIKey  # name of the header, query parameter or cookie

  schemas:
    merchandise-group:
      $ref : "../common/merchandise-group.yaml#/components/schemas/merchandise-group"

      example:
        id: "01"
        href: "https://api.armani.it/v1/merchandise-group/01"
        description:
          - language: en
            description: COAT

    list:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/merchandise-group"

      example:
        items:
          - id: "01"
            href: "https://api.armani.it/v1/merchandise-group/01"
            description:
              - language: en
                description: COAT
          - id: "02"
            href: "https://api.armani.it/v1/merchandise-group/02"
            description:
              - language: en
                description: SUITS
          - id: "03"
            href: "https://api.armani.it/v1/merchandise-group/03"
            description:
              - language: en
                description: SKIRTS/PANTS